version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - ascontiguousarray
  - asscalar
  - Asum
  - autochunking
  - beautifulsoup
  - blas
  - bokeh
  - btype
  - busa
  - cdname
  - cdval
  - cdylib
  - celerybeat
  - cmap
  - cnmf
  - cnmfviewer
  - colorcet
  - commitizen
  - coorandinates
  - csize
  - cvxpy
  - darr
  - dask
  - datashade
  - datashader
  - datashading
  - Deconvolved
  - delenv
  - denoise
  - dmypy
  - doctest
  - dpath
  - dslist
  - dtype
  - dynspread
  - ecos
  - epath
  - errorlevel
  - exitfirst
  - fhist
  - filt
  - flist
  - fmread
  - fnames
  - getaffinity
  - haya
  - holoviews
  - htmlcov
  - hvobj
  - hvsum
  - idxs
  - imread
  - Internsity
  - intpath
  - ipynb
  - isel
  - jnote
  - jsonable
  - kdim
  - kdims
  - ksize
  - linalg
  - localcluster
  - maturin
  - metas
  - minian
  - Miniscope
  - mkdocs
  - natsort
  - natsorted
  - nbfile
  - nbsplit
  - ndcurve
  - nosetests
  - NWORKERS
  - OPENBLAS
  - outpath
  - Pipfile
  - pjoin
  - popd
  - pushd
  - pyargs
  - pyarray
  - pydata
  - pyenv
  - pyfftw
  - pyfunction
  - pymetis
  - pymodule
  - pypackages
  - pytype
  - realfft
  - rechunk
  - rechunker
  - refelect
  - rerunfailures
  - rfft
  - ropeproject
  - rtds
  - scisps
  - Scrapy
  - sdist
  - setuptools
  - skvideo
  - SOURCEDIR
  - SPHINXBUILD
  - SPHINXOPTS
  - spliter
  - Spyder
  - spyderproject
  - spyproject
  - srcpath
  - subsetting
  - thres
  - tifffile
  - tophat
  - usub
  - varr
  - Viridis
  - vlist
  - webassets
  - wgts
  - xarr
ignoreWords: []
import: []
