version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - amax
  - argwhere
  - ascontiguousarray
  - asscalar
  - Asum
  - autochunking
  - beautifulsoup
  - blas
  - bokeh
  - btype
  - busa
  - cdname
  - cdval
  - cdylib
  - celerybeat
  - cmap
  - CMAPS
  - cnmf
  - cnmfviewer
  - colorcet
  - commitizen
  - coorandinates
  - csize
  - cvxpy
  - darr
  - dask
  - datashade
  - datashaded
  - datashader
  - datashading
  - Deconvolved
  - delenv
  - denoise
  - dmypy
  - doctest
  - dpath
  - dslist
  - dtype
  - dynspread
  - ecos
  - epath
  - errorlevel
  - exitfirst
  - fhist
  - filt
  - flist
  - fmread
  - fnames
  - getaffinity
  - haya
  - Holo
  - holostreams
  - holoviews
  - htmlcov
  - hvobj
  - hvres
  - hvsum
  - idxs
  - imread
  - Internsity
  - interp
  - intpath
  - ipykernel
  - ipynb
  - isel
  - jnote
  - jsonable
  - kdim
  - kdims
  - ksize
  - kstest
  - libx
  - linalg
  - localcluster
  - lsqr
  - lstsq
  - maturin
  - medpy
  - metas
  - minian
  - Miniscope
  - mkdocs
  - nanmax
  - nanmin
  - natsort
  - natsorted
  - nbfile
  - nbsphinx
  - nbsplit
  - ndcurve
  - ndimage
  - networkx
  - nosetests
  - Nsort
  - numba
  - NWORKERS
  - OPENBLAS
  - outpath
  - outputdict
  - ovly
  - Pipfile
  - pipmov
  - pjoin
  - pnwgt
  - popd
  - pushd
  - pyargs
  - pyarray
  - pydata
  - pyenv
  - pyfftw
  - pyfunction
  - pymetis
  - pymodule
  - pypackages
  - pytype
  - realfft
  - rechunk
  - rechunker
  - refelect
  - rerunfailures
  - rfft
  - ropeproject
  - rtds
  - scisps
  - Scrapy
  - sdist
  - setuptools
  - skimage
  - skvideo
  - SOURCEDIR
  - SPHINXBUILD
  - SPHINXOPTS
  - spliter
  - Spyder
  - spyderproject
  - spyproject
  - srcpath
  - strm
  - subsetting
  - subviews
  - thres
  - tifffile
  - timepoint
  - timepoints
  - toeplitz
  - tophat
  - ultrafast
  - usub
  - VARARRAY
  - varr
  - varray
  - vaviewer
  - vcodec
  - vdims
  - Viridis
  - VLINE
  - vlist
  - vname
  - vpath
  - webassets
  - wgts
  - xarr
  - xarray
  - XLABEL
  - YLABEL
ignoreWords: []
import: []
