"""Shared visualization literals (sizes, palettes, titles, widget geometry)."""

from __future__ import annotations

from enum import StrEnum


class ImagePalette(StrEnum):
    """Colormap names for HoloViews / Bokeh-style ``cmap=`` arguments."""

    VIRIDIS_DISPLAY = "Viridis"
    VIRIDIS_BOKEH = "viridis"


class SummaryStat(StrEnum):
    """Allowed ``VArrayViewer`` summary curve names."""

    MEAN = "mean"
    MAX = "max"
    MIN = "min"
    DIFF = "diff"


# --- Preprocessing (`visualize_preprocess`)
PREPROCESS_FRAME_WIDTH = 500
PREPROCESS_IMAGE_TITLE = "Image {label} {group} {dimensions}"
PREPROCESS_CONTOURS_TITLE = "Contours {label} {group} {dimensions}"

# --- Datashader / Nd-curve overlay
DATASHADE_NDCURVE_MIN_ALPHA = 200

# --- Seeds / GMM / spatial / temporal pipeline plots
SEEDS_FRAME_WIDTH = 600
SEEDS_POINTS_UNMASKED_COLOR = "white"
SEEDS_MASK_FALSE_COLOR = "red"
GMM_FIG_WIDTH = 500
GMM_FIG_HEIGHT = 350
GMM_HIST_FILL_ALPHA = 0.6
GMM_HIST_FILL_COLOR = "gray"

SPATIAL_IMAGE_FRAME_WIDTH = 400
SPATIAL_TEMPORAL_CURVE_FRAME_WIDTH = 500
SPATIAL_TEMPORAL_CURVE_FRAME_HEIGHT = 50
SPATIAL_POINTS_SIZE = 8
SPATIAL_POINTS_FILL_ALPHA = 0.2

TEMPORAL_UNIT_MAP_FRAME_HEIGHT = 400
TEMPORAL_UNIT_MAP_FRAME_WIDTH = 1000
TEMPORAL_SPATIAL_FOOTPRINT_FRAME_WIDTH = 500
TEMPORAL_PULSE_PREVIEW_LEN = 500

# --- Motion
MOTION_IMAGE_FRAME_WIDTH = 500
MOTION_IMAGE_ASPECT = 3
MOTION_CURVE_FRAME_WIDTH = 500
MOTION_CURVE_ASPECT = 2
MOTION_DIVERGING_CMAP = "RdBu"

# --- VArrayViewer
VARARRAY_FRAME_WIDTH = 500
VARARRAY_HIST_SIDE_WIDTH = 150
VARARRAY_HIST_NUM_BINS = 50
VARARRAY_HIST_XLABEL = "fluorescence"
VARARRAY_HIST_YLABEL = "freq"
VARARRAY_SUMMARY_ASPECT = 3
VARARRAY_SUMMARY_RGB_HEIGHT_FLOOR = 120
VARARRAY_POLYGON_FILL_ALPHA = 0.3
VARARRAY_POLYGON_LINE_COLOR = "white"
VARARRAY_VLINE_COLOR = "red"

# --- Panel widgets (VArrayViewer toolbar)
PLAYER_WIDTH = 650
PLAYER_HEIGHT = 90
PLAYER_INTERVAL_MS = 10
UPDATE_MASK_BUTTON_WIDTH = 100
UPDATE_MASK_BUTTON_HEIGHT = 30

# --- Meta selectors (`_viewer_helpers`)
META_SELECT_WIDGET_HEIGHT = 45
META_SELECT_WIDGET_WIDTH = 120

# --- Panel layout
PANEL_SIZING_STRETCH_WIDTH = "stretch_width"

__all__ = [
    "DATASHADE_NDCURVE_MIN_ALPHA",
    "GMM_FIG_HEIGHT",
    "GMM_FIG_WIDTH",
    "GMM_HIST_FILL_ALPHA",
    "GMM_HIST_FILL_COLOR",
    "ImagePalette",
    "META_SELECT_WIDGET_HEIGHT",
    "META_SELECT_WIDGET_WIDTH",
    "MOTION_CURVE_ASPECT",
    "MOTION_CURVE_FRAME_WIDTH",
    "MOTION_DIVERGING_CMAP",
    "MOTION_IMAGE_ASPECT",
    "MOTION_IMAGE_FRAME_WIDTH",
    "PANEL_SIZING_STRETCH_WIDTH",
    "PLAYER_HEIGHT",
    "PLAYER_INTERVAL_MS",
    "PLAYER_WIDTH",
    "PREPROCESS_CONTOURS_TITLE",
    "PREPROCESS_FRAME_WIDTH",
    "PREPROCESS_IMAGE_TITLE",
    "SEEDS_FRAME_WIDTH",
    "SEEDS_MASK_FALSE_COLOR",
    "SEEDS_POINTS_UNMASKED_COLOR",
    "SPATIAL_IMAGE_FRAME_WIDTH",
    "SPATIAL_POINTS_FILL_ALPHA",
    "SPATIAL_POINTS_SIZE",
    "SPATIAL_TEMPORAL_CURVE_FRAME_HEIGHT",
    "SPATIAL_TEMPORAL_CURVE_FRAME_WIDTH",
    "SummaryStat",
    "TEMPORAL_PULSE_PREVIEW_LEN",
    "TEMPORAL_SPATIAL_FOOTPRINT_FRAME_WIDTH",
    "TEMPORAL_UNIT_MAP_FRAME_HEIGHT",
    "TEMPORAL_UNIT_MAP_FRAME_WIDTH",
    "UPDATE_MASK_BUTTON_HEIGHT",
    "UPDATE_MASK_BUTTON_WIDTH",
    "VARARRAY_FRAME_WIDTH",
    "VARARRAY_HIST_NUM_BINS",
    "VARARRAY_HIST_SIDE_WIDTH",
    "VARARRAY_HIST_XLABEL",
    "VARARRAY_HIST_YLABEL",
    "VARARRAY_POLYGON_FILL_ALPHA",
    "VARARRAY_POLYGON_LINE_COLOR",
    "VARARRAY_SUMMARY_ASPECT",
    "VARARRAY_SUMMARY_RGB_HEIGHT_FLOOR",
    "VARARRAY_VLINE_COLOR",
]
